version: '3'

services:
  login-system:
    container_name: login-system
    restart: always
    build:
      context: .
      target: final
    ports:
      - 8000:8000
    env_file: ./backend/.env
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - database:/data/db
volumes:
  database: