version: '3'

services:
  login-system:
    container_name: login-system
    build:
      context: .
      target: final
    ports:
      - '8000:8000'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    env_file: ./backend/.env
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example