version: '3'

services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - database:/data/db
    networks: 
      - db
volumes:
  database:
networks: 
  db: 
    external: true
