version: '3'

services:
  login-system:
    container_name: login-system
    restart: always
    build: .
    ports:
      - '8000:8000'
    env_file: .env
    # depends_on:
    #   - mongo
    networks: 
      - db
networks: 
  db: 
    external: true